image: alpine/edge
oauth: git.sr.ht/OBJECTS:RW git.sr.ht/REPOSITORIES:RO git.sr.ht/PROFILE:RO
packages:
    - git
    - go
    - make
    - musl-dev
    - scdoc
    - hut
sources:
    - https://git.sr.ht/~gpanders/ijq
environment:
    REPO_ID: 23987
    GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
triggers:
    - action: email
      condition: failure
      to: Gregory Anders <greg@gpanders.com>
tasks:
    - setup: |
        echo 'cd ijq' >> ~/.buildenv
    - test: |
        make test
    - nopr: |
        # Don't run on GitHub PRs
        [ "$BUILD_SUBMITTER" = 'git.sr.ht' ] || complete-build
    - build: |
        tag=$(git describe --exact-match 2>/dev/null || true)
        if [ -z "$tag" ]; then
            echo "Current commit is not a tag; not building anything"
            exit 0
        fi

        version=$(echo "$tag" | tr -d 'v')
        mkdir ijq-"$version"

        build() {
            os="$1"
            arch="$2"
            make GOOS="$os" GOARCH="$arch" clean all
            cp ijq ijq.1 COPYING ijq-"$version"/

            if [ "$os" = windows ]; then
                mv ijq-"$version"/ijq{,.exe}
            fi

            tar czf ijq-"$version"-"$os"-"$arch".tar.gz ijq-"$version"
            hut git artifact upload --rev "$tag" ijq-"$version"-"$os"-"$arch".tar.gz
        }

        build darwin amd64
        build darwin arm64
        build linux amd64
        build windows amd64
