image: alpine/edge
packages:
    - git
    - go
    - make
    - musl-dev
sources:
    - https://git.sr.ht/~gpanders/ijq
secrets:
    - 78f39fb6-1185-492f-9c21-f755e10b5e5d
environment:
    GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
triggers:
    - action: email
      condition: failure
      to: Greg Anders <admin@gpanders.com>
tasks:
    - mirror: |
        cd ijq
        git push --force --mirror git@github.com:gpanders/ijq
    - build: |
        cd ijq
        make
        tar czf ijq-linux-x86_64.tar.gz ijq
artifacts:
    - ijq/ijq-linux-x86_64.tar.gz
