name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test -v -coverprofile=./cover.out ./...

  race-test:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test -race ./...
